// Generated by CoffeeScript 2.3.0
(function() {
  var fs, https, main;

  https = require("https");

  fs = require("fs");

  main = async function() {
    var apiStr, data, tokens;
    apiStr = "https://api.ethplorer.io/getTop?apiKey=freekey&criteria=cap";
    data = (await (new Promise(function(resolve, reject) {
      return https.get(apiStr, function(res) {
        var rawData;
        rawData = "";
        res.on("data", function(chunk) {
          return rawData += chunk;
        });
        return res.on("end", function() {
          var parsedData;
          parsedData = JSON.parse(rawData);
          return resolve(parsedData);
        });
      }).on("error", reject);
    })));
    tokens = data.tokens.map(function(token) {
      if (token.decimals >= 11) {
        return {
          name: token.name,
          symbol: token.symbol,
          decimals: token.decimals
        };
      }
    });
    return fs.writeFileSync("./eth/deployment_configs/tokens.json", JSON.stringify(tokens));
  };

  main();

}).call(this);
