// Generated by CoffeeScript 2.3.2
(function() {
  var BETOKEN_ADDR, BetokenFund, ERC20, TOKENS, TOKEN_FACTORY_ADDR, TestTokenFactory;

  BetokenFund = artifacts.require("BetokenFund");

  TestTokenFactory = artifacts.require("TestTokenFactory");

  ERC20 = artifacts.require("ERC20");

  BETOKEN_ADDR = "0x5910d5ABD4d5fD58b39957664Cd9735CbfE42bF0";

  TOKEN_FACTORY_ADDR = "0x76fc4b929325D04f5e3F3724eFDDFB45B52d3160";

  TOKENS = require("../deployment_configs/kn_token_symbols.json");

  module.exports = async function(callback) {
    var betoken, i, len, results, token, tokenFactory;
    tokenFactory = (await TestTokenFactory.at(TOKEN_FACTORY_ADDR));
    betoken = (await BetokenFund.at(BETOKEN_ADDR));
    results = [];
    for (i = 0, len = TOKENS.length; i < len; i++) {
      token = TOKENS[i];
      results.push((await tokenFactory.getToken(token).then(async function(_addr) {
        var balance;
        balance = (await ((await ERC20.at(_addr))).balanceOf(BETOKEN_ADDR));
        if (balance > 0) {
          console.log(`${token}: ${_addr}`);
          return console.log(`Balance of ${token}: ${balance}`);
        }
      })));
    }
    return results;
  };

  //await betoken.sellLeftoverToken(_addr)

}).call(this);
