// Generated by CoffeeScript 2.3.0
(function() {
  var BetokenFund, ControlToken, ShareToken, config, dev_fee_address, old_address;

  BetokenFund = artifacts.require("BetokenFund");

  ControlToken = artifacts.require("ControlToken");

  ShareToken = artifacts.require("ShareToken");

  config = require("../deployment_configs/testnet.json");

  dev_fee_address = "0xDbE011EB3fe8C77C94Cc9d9EC176BDddC937F425";

  old_address = "0x8562D0E4E2853493E5d908Ec1caAa05604d48605";

  module.exports = function(callback) {
    var controlTokenAddr, new_contract, old_contract;
    old_contract = BetokenFund.at(old_address);
    new_contract = null;
    controlTokenAddr = null;
    return old_contract.controlTokenAddr().then(function(_addr) {
      return controlTokenAddr = _addr;
    }).then(function() {
      //Deploy new BetokenFund
      return ShareToken.new().then(function(_shareToken) {
        console.log("Created new ShareToken at " + _shareToken.address);
        return BetokenFund.new(controlTokenAddr, _shareToken.address, config.kyberAddress, dev_fee_address, config.phaseLengths, config.commissionRate, config.developerFeeProportion, config.functionCallReward, old_address).then(function(_instance) {
          new_contract = _instance;
          return console.log("Created new BetokenFund at " + _instance.address);
        }).then(function() {
          _shareToken.transferOwnership(new_contract.address);
          return console.log("Transferred ownership of " + _shareToken.address + " to " + new_contract.address);
        });
      });
    }).then(function() {
      //Transfer ownership
      old_contract.changeControlTokenOwner(new_contract.address);
      return console.log("Transferred ownership of " + controlTokenAddr + " to " + new_contract.address);
    });
  };

}).call(this);
