// Generated by CoffeeScript 2.2.0
(function() {
  var BetokenFund, ControlToken, config, dev_fee_address, old_address, start_cycle_number;

  BetokenFund = artifacts.require("BetokenFund");

  ControlToken = artifacts.require("ControlToken");

  config = require("../deployment_configs/testnet.json");

  dev_fee_address = "0xDbE011EB3fe8C77C94Cc9d9EC176BDddC937F425";

  old_address = "0x8562D0E4E2853493E5d908Ec1caAa05604d48605";

  start_cycle_number = 0;

  module.exports = function(callback) {
    var new_contract, old_contract;
    old_contract = BetokenFund.at(old_address);
    new_contract = null;
    return old_contract.pause().then(function() {
      //Deploy new BetokenFund
      return BetokenFund.new(config.kyberAddress, dev_fee_address, config.timeOfChangeMaking, config.timeOfProposalMaking, config.timeOfWaiting, config.minStakeProportion, config.maxProposals, config.commissionRate, config.developerFeeProportion, config.maxProposalsPerMember, start_cycle_number).then(function(_instance) { //KyberNetwork address //developerFeeAccount //2 * 24 * 3600, #timeOfChangeMaking //2 * 24 * 3600, #timeOfProposalMaking //timeOfWaiting //minStakeProportion //maxProposals //commissionRate //developerFeeProportion //maxProposalsPerMember //cycleNumber
        new_contract = _instance;
        return console.log("Created new BetokenFund at " + _instance.address);
      });
    }).then(function() {
      var kairoAddr, participants;
      //Transfer participants data
      participants = [];
      kairoAddr = null;
      old_contract.participantsCount().then(function(_count) {
        var count, getAllItems, getItem, id;
        count = _count.toNumber();
        if (count === 0) {
          return;
        }
        participants = new Array(count);
        getItem = function(id) {
          return old_contract.participants(id).then(function(_item) {
            return new Promise(function(fullfill, reject) {
              if (typeof _item !== null) {
                participants[id] = _item;
                fullfill();
              } else {
                reject();
              }
            });
          });
        };
        getAllItems = (function() {
          var i, ref, results;
          results = [];
          for (id = i = 0, ref = count - 1; undefined !== 0 && (0 <= ref ? 0 <= i && i <= ref : 0 >= i && i >= ref); id = 0 <= ref ? ++i : --i) {
            results.push(getItem(id));
          }
          return results;
        })();
        return Promise.all(getAllItems);
      }).then(function() {
        new_contract.initializeParticipants(participants);
        return console.log("Initializing participant list...");
      //Initialize subcontracts for new BetokenFund
      }).then(function() {
        return old_contract.controlTokenAddr();
      }).then(function(_addr) {
        return kairoAddr = _addr;
      }).then(function() {
        return new_contract.initializeSubcontracts(kairoAddr);
      });
      //Transfer ownership
      return old_contract.changeControlTokenOwner(new_contract.address);
    });
  };

}).call(this);

//# sourceMappingURL=upgrade_retain_kairo_oraclize.js.map
