// Generated by CoffeeScript 2.2.0
(function() {
  var BetokenFund, ControlToken, OraclizeHandler, config, dev_fee_address;

  BetokenFund = artifacts.require("BetokenFund");

  ControlToken = artifacts.require("ControlToken");

  OraclizeHandler = artifacts.require("OraclizeHandler");

  config = require("../deployment_configs/testnet.json");

  dev_fee_address = "0xeabffa328d2e2340384ddfc128a78dd7964c6edb";

  module.exports = function(callback) {
    var new_contract, old_contract;
    old_contract = null;
    new_contract = null;
    //Get old BetokenFund
    return BetokenFund.deployed().then(function(_instance) {
      return old_contract = _instance;
    //Uncommemt on Testnet or Mainnet (anywhere with an EtherDelta contract)
    }).then(function() {}).then(function() { //old_contract.pause()
      //Deploy new BetokenFund
      return BetokenFund.new(config.etherDeltaAddress, dev_fee_address, config.precision, config.timeOfChangeMaking, config.timeOfProposalMaking, config.timeOfWaiting, config.timeOfSellOrderWaiting, config.minStakeProportion, config.maxProposals, config.commissionRate, config.orderExpirationTimeInBlocks, config.developerFeeProportion, config.maxProposalsPerMember).then(function(_instance) { //Ethdelta address //developerFeeAccount //precision //2 * 24 * 3600, #timeOfChangeMaking //2 * 24 * 3600, #timeOfProposalMaking //timeOfWaiting //timeOfSellOrderWaiting //minStakeProportion //maxProposals //commissionRate //3600 / 20, #orderExpirationTimeInBlocks //developerFeeProportion //maxProposalsPerMember
        return new_contract = _instance;
      });
    }).then(function() {
      var kairoAddr, oraclizeAddr, participants;
      //Transfer participants data
      participants = [];
      oraclizeAddr = null;
      kairoAddr = null;
      old_contract.participantsCount().then(function(_count) {
        var count, getAllItems, getItem, id;
        count = _count.toNumber();
        if (count === 0) {
          return;
        }
        participants = new Array(count);
        getItem = function(id) {
          return old_contract.participants(id).then(function(_item) {
            return new Promise(function(fullfill, reject) {
              if (typeof _item !== null) {
                participants[id] = _item;
                fullfill();
              } else {
                reject();
              }
            });
          });
        };
        getAllItems = (function() {
          var i, ref, results;
          results = [];
          for (id = i = 0, ref = count - 1; undefined !== 0 && (0 <= ref ? 0 <= i && i <= ref : 0 >= i && i >= ref); id = 0 <= ref ? ++i : --i) {
            results.push(getItem(id));
          }
          return results;
        })();
        return Promise.all(getAllItems);
      }).then(function() {
        return new_contract.initializeParticipants(participants);
      //Initialize subcontracts for new BetokenFund
      }).then(function() {
        return old_contract.controlTokenAddr();
      }).then(function(_addr) {
        return kairoAddr = _addr;
      }).then(function() {
        return old_contract.oraclizeAddr();
      }).then(function(_addr) {
        return oraclizeAddr = _addr;
      }).then(function() {
        return new_contract.initializeSubcontracts(kairoAddr, oraclizeAddr);
      });
      //Transfer ownership
      old_contract.changeOraclizeOwner(new_contract.address);
      return old_contract.changeControlTokenOwner(new_contract.address);
    });
  };

}).call(this);

//# sourceMappingURL=upgrade_retain_kairo_oraclize.js.map
