// Generated by CoffeeScript 2.1.1
//Import web3
var Web3, getDefaultAccount, web3;

Web3 = require('web3');

web3 = window.web3;

if (typeof web3 !== void 0) {
  web3 = new Web3(web3.currentProvider);
} else {
  web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
}

getDefaultAccount = function() {
  return web3.eth.getAccounts().then(function(accounts) {
    return web3.eth.defaultAccount = accounts[0];
  });
};

/**
 * Constructs an abstraction of Betoken contracts
 * @param {String} _address the GroupFund contract's address
 */
export var Betoken = function(_address) {
  var self;
  self = this;
  self.contracts = {
    groupFund: null,
    controlToken: null
  };
  self.addrs = {
    groupFund: null,
    controlToken: null
  };
  /*
  Getters
  */
  /**
   * Gets a primitive variable in GroupFund
   * @param  {String} _varName the name of the primitive variable
   * @return {Promise}          .then((_value)->)
   */
  self.getPrimitiveVar = function(_varName) {
    return self.contracts.groupFund.methods[_varName]().call();
  };
  /**
   * Calls a mapping or an array in GroupFund
   * @param  {String} _name name of the mapping/array
   * @param  {Any} _input       the input
   * @return {Promise}              .then((_value)->)
   */
  self.getMappingOrArrayItem = function(_name, _input) {
    return self.contracts.groupFund.methods[_name](_input).call();
  };
  /**
   * Calls a double mapping in GroupFund
   * @param  {String} _mappingName name of the mapping
   * @param  {Any} _input1      the first input
   * @param  {Any} _input2      the second input
   * @return {Promise}              .then((_value)->)
   */
  self.getDoubleMapping = function(_mappingName, _input1, _input2) {
    return self.contracts.groupFund.methods[_mappingName](_input1, _input2).call();
  };
  /**
   * Gets the Kairo balance of an address
   * @param  {String} _address the address whose balance we're getting
   * @return {Promise}          .then((_value)->)
   */
  self.getKairoBalance = function(_address) {
    return self.contracts.controlToken.methods.balanceOf(_address).call();
  };
  self.getKairoTotalSupply = function() {
    return self.contracts.controlToken.methods.totalSupply().call();
  };
  /**
   * Gets an entire array
   * @param  {String} _name name of the array
   * @return {Promise}       .then((_array)->)
   */
  self.getArray = function(_name) {
    var array;
    array = [];
    return self.contracts.groupFund.methods[`${_name}Count`]().call().then(function(_count) {
      var count, getAllItems, getItem, id;
      count = +_count;
      if (count === 0) {
        return [];
      }
      array = new Array(count);
      getItem = function(id) {
        return self.contracts.groupFund.methods[_name](id).call().then(function(_item) {
          return new Promise(function(fullfill, reject) {
            if (typeof _item !== null) {
              array[id] = _item;
              fullfill();
            } else {
              reject();
            }
          });
        });
      };
      getAllItems = (function() {
        var i, ref, results;
        results = [];
        for (id = i = 0, ref = count - 1; 0 <= ref ? i <= ref : i >= ref; id = 0 <= ref ? ++i : --i) {
          results.push(getItem(id));
        }
        return results;
      })();
      return Promise.all(getAllItems);
    }).then(function() {
      return array;
    });
  };
  /*
  Phase handlers
  */
  /**
   * Ends the current phase
   * @return {Promise} .then(()->)
   */
  self.endPhase = function() {
    var funcName;
    funcName = null;
    return self.getPrimitiveVar("cyclePhase").then(function(_cyclePhase) {
      _cyclePhase = +_cyclePhase;
      switch (_cyclePhase) {
        case 0:
          return funcName = "endChangeMakingTime";
        case 1:
          return funcName = "endProposalMakingTime";
        case 2:
          return funcName = "endCycle";
        case 3:
          return funcName = "finalizeEndCycle";
        case 4:
          return funcName = "startNewCycle";
      }
    }).then(function() {
      return getDefaultAccount();
    }).then(function() {
      return self.contracts.groupFund.methods[funcName]().send({
        from: web3.eth.defaultAccount
      });
    });
  };
  /*
  ChangeMakingTime functions
  */
  /**
   * Allows user to deposit into the GroupFund
   * @param  {BigNumber} _amountInWeis the deposit amount
   * @return {Promise}               .then(()->)
   */
  self.deposit = function(_amountInWeis) {
    var funcSignature;
    funcSignature = web3.eth.abi.encodeFunctionSignature("deposit()");
    return getDefaultAccount().then(function() {
      return web3.eth.sendTransaction({
        from: web3.eth.defaultAccount,
        to: self.addrs.groupFund,
        value: _amountInWeis,
        data: funcSignature
      });
    });
  };
  /**
   * Allows user to withdraw from GroupFund balance
   * @param  {BigNumber} _amountInWeis the withdrawl amount
   * @return {Promise}               .then(()->)
   */
  self.withdraw = function(_amountInWeis) {
    return getDefaultAccount().then(function() {
      return self.contracts.groupFund.methods.withdraw(_amountInWeis).send({
        from: web3.eth.defaultAccount
      });
    });
  };
  /*
  ProposalMakingTime functions
  */
  /**
   * Creates proposal
   * @param  {String} _tokenAddress the token address
   * @param  {String} _tokenSymbol  the token symbol (ticker)
   * @param  {Number} _tokenDecimals the number of decimals the token uses
   * @param  {BigNumber} _stakeInWeis the investment amount
   * @return {Promise}               .then(()->)
   */
  self.createProposal = function(_tokenAddress, _tokenSymbol, _tokenDecimals, _stakeInWeis) {
    return getDefaultAccount().then(function() {
      return self.contracts.groupFund.methods.createProposal(_tokenAddress, _tokenSymbol, _tokenDecimals, _stakeInWeis).send({
        from: web3.eth.defaultAccount
      });
    });
  };
  /**
   * Supports proposal
   * @param  {Integer} _proposalId   the proposal ID
   * @param  {BigNumber} _stakeInWeis the investment amount
   * @return {Promise}               .then(()->)
   */
  self.supportProposal = function(_proposalId, _stakeInWeis) {
    return getDefaultAccount().then(function() {
      return self.contracts.groupFund.methods.supportProposal(_proposalId, _stakeInWeis).send({
        from: web3.eth.defaultAccount
      });
    });
  };
  /**
   * Cancels user's support of a proposal
   * @param  {Integer} _proposalId the proposal ID
   * @return {Promise}             .then(()->)
   */
  self.cancelSupport = function(_proposalId) {
    return getDefaultAccount().then(function() {
      return self.contracts.groupFund.methods.cancelProposalSupport(_proposalId).send({
        from: web3.eth.defaultAccount
      });
    });
  };
  self.getCurrentAccount = function() {
    return getDefaultAccount().then(function() {
      return web3.eth.defaultAccount;
    });
  };
  /*
  Object Initialization
  */
  self.init = function() {
    var groupFundABI;
    //Initialize GroupFund contract
    self.addrs.groupFund = _address;
    groupFundABI = require("./abi/GroupFund.json").abi;
    self.contracts.groupFund = new web3.eth.Contract(groupFundABI, self.addrs.groupFund);
    //Get ControlToken address
    return self.contracts.groupFund.methods.controlTokenAddr().call().then(function(_controlTokenAddr) {
      var controlTokenABI;
      //Initialize ControlToken contract
      self.addrs.controlToken = _controlTokenAddr;
      controlTokenABI = require("./abi/ControlToken.json").abi;
      return self.contracts.controlToken = new web3.eth.Contract(controlTokenABI, self.addrs.controlToken);
    });
  };
  return self;
};

//# sourceMappingURL=betoken.js.map
