// Generated by CoffeeScript 2.0.2
var Web3, betoken, betoken_addr, displayedKairoBalance, kairoBalance, kairoTotalSupply, userAddress, web3;

import './body.html';

import './body.css';

import './tablesort.js';

import {
  Betoken
} from '../objects/betoken.js';

import Chart from 'chart.js';

//Import web3
Web3 = require('web3');

web3 = window.web3;

if (typeof web3 !== void 0) {
  web3 = new Web3(web3.currentProvider);
} else {
  web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
}

betoken_addr = "";

betoken = new Betoken(betoken_addr);

userAddress = new ReactiveVar("");

kairoBalance = new ReactiveVar("");

kairoTotalSupply = new ReactiveVar("");

displayedKairoBalance = new ReactiveVar("");

$('document').ready(function() {
  var ctx, myChart;
  $('.menu .item').tab();
  $('table').tablesort();
  ctx = document.getElementById("myChart");
  return myChart = new Chart(ctx, {
    type: 'line',
    data: {
      datasets: [
        {
          label: "ROI Per Cycle",
          backgroundColor: 'rgba(0, 0, 100, 0.5)',
          borderColor: 'rgba(0, 0, 100, 1)',
          data: [
            {
              x: 1,
              y: 10
            },
            {
              x: 2,
              y: 13
            },
            {
              x: 3,
              y: 20
            }
          ]
        }
      ]
    },
    options: {
      scales: {
        xAxes: [
          {
            type: 'linear',
            position: 'bottom',
            scaleLabel: {
              display: true,
              labelString: 'Investment Cycle'
            },
            ticks: {
              stepSize: 1
            }
          }
        ],
        yAxes: [
          {
            type: 'linear',
            position: 'left',
            scaleLabel: {
              display: true,
              labelString: 'Percent'
            },
            ticks: {
              beginAtZero: true
            }
          }
        ]
      }
    }
  });
});

Template.body.onCreated(function() {
  return betoken.getCurrentAccount().then(function(result) {
    return userAddress.set(result);
  }).then(function() {
    return betoken.getKairoBalance(userAddress.get());
  }).then(function(result) {
    kairoBalance.set(result);
    return displayedKairoBalance.set(web3.util.fromWei(result, "ether"));
  }).then(function() {
    return betoken.getKairoTotalSupply();
  }).then(function(result) {
    return kairoTotalSupply.set(result);
  });
});

Template.phase_indicator.helpers({
  phase_active: function(index) {
    var isActive;
    isActive = new ReactiveVar("");
    betoken.getPrimitiveVar("cyclePhase").then(function(result) {
      if (result === index) {
        return isActive.set("active");
      }
    });
    return isActive.get();
  }
});

Template.sidebar.helpers({
  user_address: function() {
    return userAddress.get();
  },
  user_balance: function() {
    var balance;
    balance = new ReactiveVar("");
    betoken.getMappingOrArrayItem("balanceOf", userAddress.get()).then(function(result) {
      return balance.set(web3.util.fromWei(result, "ether"));
    });
    return balance.get();
  },
  user_kairo_balance: function() {
    return displayedKairoBalance.get();
  }
});

Template.sidebar.events({
  "click .kairo_unit_switch": function(event) {
    var kairoBalanceInKRO, kairoSupplyInKRO;
    if (this.isOn) {
      kairoBalanceInKRO = Number.parseFloat(web3.util.fromWei(kairoBalance.get(), "ether"));
      kairoSupplyInKRO = Number.parseFloat(web3.util.fromWei(kairoTotalSupply.get(), "ether"));
      displayedKairoBalance.set(kairoBalanceInKRO / kairoSupplyInKRO * 100);
      return this.isOn = false;
    } else {
      displayedKairoBalance.set(web3.util.fromWei(kairoBalance.get(), "ether"));
      return this.isOn = true;
    }
  }
});
