// Generated by CoffeeScript 2.2.2
(function() {
  var BetokenFund, ControlToken, ShareToken, config;

  BetokenFund = artifacts.require("BetokenFund");

  ControlToken = artifacts.require("ControlToken");

  ShareToken = artifacts.require("ShareToken");

  config = require("../deployment_configs/testnet.json");

  module.exports = function(deployer, network, accounts) {
    return deployer.deploy([ControlToken, ShareToken]).then(function() {
      return deployer.deploy(BetokenFund, ControlToken.address, ShareToken.address, config.kyberAddress, accounts[0], config.phaseLengths, config.commissionRate, config.developerFeeProportion, config.functionCallReward, "0x0");
    }).then(function() {
      return ControlToken.deployed().then(function(instance) {
        return instance.transferOwnership(BetokenFund.address);
      });
    }).then(function() {
      return ShareToken.deployed().then(function(instance) {
        return instance.transferOwnership(BetokenFund.address);
      });
    });
  };

}).call(this);

//# sourceMappingURL=2_deploy_contracts.js.map
