// Generated by CoffeeScript 2.2.0
(function() {
  var BetokenFund, ControlToken, config;

  BetokenFund = artifacts.require("BetokenFund");

  ControlToken = artifacts.require("ControlToken");

  config = require("../deployment_configs/testnet.json");

  module.exports = function(deployer, network, accounts) {
    return deployer.deploy([
      [
        BetokenFund,
        config.kyberAddress, //KyberNetwork address
        accounts[0],
        config.timeOfChangeMaking, //2 * 24 * 3600, #timeOfChangeMaking
        config.timeOfProposalMaking, //2 * 24 * 3600, #timeOfProposalMaking
        config.timeOfWaiting, //timeOfWaiting
        config.minStakeProportion, //minStakeProportion
        config.maxProposals, //maxProposals
        config.commissionRate, //commissionRate
        config.developerFeeProportion, //developerFeeProportion
        config.maxProposalsPerMember, //maxProposalsPerMember
        0 //cycleNumber
      ],
      [ControlToken]
    ]).then(function() {
      return ControlToken.deployed().then(function(instance) {
        return instance.transferOwnership(BetokenFund.address);
      });
    }).then(function() {
      return BetokenFund.deployed().then(function(instance) {
        return instance.initializeSubcontracts(ControlToken.address);
      });
    });
  };

}).call(this);

//# sourceMappingURL=2_deploy_contracts.js.map
